### ISSUE TITLE
explore outliers

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/open-solution-home-credit#101]

**Comment by pknut** [comment]
* bureau 'DAYS_ENDDATE_FACT' 
extreme value = -42023 (count = 1) (_42023 days > 115 years_)
other values > -3050 (_~-8.4 y_)
* bureau 'DAYS_CREDIT_UPDATE'
extreme values < -41000 (count = 95) (_41000 days > 110 years_)
other values > -3000 (_~-8.2 y_)

**Comment by pknut** [comment]
* application 'AMT_REQ_CREDIT_BUREAU_QRT'
extreme value = 261 (count = 1)
other values < 20
