### ISSUE TITLE
diversity - Neural network

### ISSUE THREAD

**Issue by kstrzala** [neptune-ml/open-solution-home-credit#136]

**Comment by yotamco100** [comment]
hey guys, im a DL beginner... Any chance I can join this issue?

**Comment by kamil-kaczmarek** [comment]
@jakubczakon ^^ what do you thing?

**Comment by yotamco100** [comment]
I just made the object because I'm way too noobish to actually try my hand. Every architecture I try to build achieves mediocre results so yeah. Decided to just outline it for now.
