### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by wongalvis** [neptune-ml/open-solution-home-credit#168]
What do we need to do to use GPU for training?
I've changed the device params in neptune.yaml to "gpu", but nvidia-smi shows that the GPU is not being used.

That said, I might be checking nvidia-smi at the wrong step, I want to confirm how can I check the model is being trained by looking at the console log outputs.

**Comment by jakubczakon** [comment]
I am training on cpu so not 100% sure but i would suggest to check whether  lightgbm gpu binary is installed. Sometimes you have both cpu and gpu options available (like in tensorflow).
