### ISSUE TITLE
xgboost failing to import with requirements.txt

### ISSUE THREAD

**Issue by harrisonsjones** [neptune-ml/open-solution-home-credit#188]
I am receiving the error message `"Files/directories (from PKG-INFO) not found in C:\Users\harri\AppData\Local\Temp\pip-install-eorbpo_v\xgboost\pip-egg-info"` when trying to run 
`pip3 install -r requirements.txt`

I was able to install xgboost through the method at this SO answer: https://stackoverflow.com/questions/33749735/how-to-install-xgboost-package-in-python-windows-platform/41274589#41274589 
but now I'm receiving some other error messages when I try to run main.py so I'm not sure it was the correct solution for this purpose.

**Comment by kamil-kaczmarek** [comment]
Hi @harrisonsjones,

First thing that I would try is to clean your `Temp` directory, namely: `C:\Users\harri\AppData\Local\Temp`.

As usual, I strongly recommend to use Ubuntu 16.04. In your case you can try Virtual Box or VMware Player.
