### ISSUE TITLE
Notebook Updated ?

### ISSUE THREAD

**Issue by Shiro-LK** [neptune-ml/open-solution-home-credit#196]
Hello,

Thank you for sharing your project, it is interesting !
I have a question regarding the different notebook where there are some preprocessing (cleaning) and creation of new features (hand craft and aggregating). I think the notebook are not updated if we compare to the code. For instance, if we look at the application data, we see 5 cleaning in the code, but in the notebook only two are available. It is forecast to update them ? It is more easy to understand all the data engineering with a notebook than a complete code.

**Comment by jakubczakon** [comment]
You are right @Shiro-LK. There could easily be a difference between those. We will definitely clean it up after the competition has finished but for now you are more then welcome to submit a PR with that unified (or simply wait till the end :) ) .

**Comment by jakubczakon** [comment]
@Shiro-LK notebooks were updated so you can run them if you like.
