### ISSUE TITLE
How to export the feature correlation?

### ISSUE THREAD

**Issue by OsloAI** [neptune-ml/open-solution-home-credit#209]
Dear,

Could you tell me how to export the feature correlation? I saw some features in your wiki with some correlation scores. I would like to know how can you know the score? By the way, what is the scoring math metric you used? Thanks

**Comment by kamil-kaczmarek** [comment]
@jakubczakon or @pknut can you help? ^^

**Comment by jakubczakon** [comment]
@OsloAI

**Comment by OsloAI** [comment]
Thanks for your reply. Could you see below the pic? does the left score is AUC Score? 
![image](https://user-images.githubusercontent.com/43272829/47216757-52ae8100-d3a6-11e8-9bf9-6310a6b84898.png)

**Comment by jakubczakon** [comment]
@OsloAI 
I am glad I could be of help!

The numbers on the right are correlations. AUC scores are reported in the readme and wiki.
